---
- hosts: local
  become: yes

  vars:
    local_config_path: "./gost-config-local.json"
    remote_config_file_path: "/opt/gost"

    destination_server_ip: "2.1.1.76"
    # destination_server_port: "your_destination_server_port"
    udp_destination_server_ip: "2.1.1.76"
    # udp_destination_server_port: "your_udp_destination_server_port"


  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      retries: 5

    - name: Install Git
      package:
        name: git

    - name: Install Go
      package:
        name: golang-go

    - name: Clone gost repository
      git:
        repo: https://github.com/ginuerzh/gost.git
        dest: /opt

    - name: Build gost
      command: "cd /opt/gost/cmd/gost && go build"

    - name: Copy Gost configuration template
      ansible.builtin.template:
        src: "./gost-config-local.json"
        dest: "/opt/gost/gost-config-local.json"
      tags:
        - copy_config

    - name: Run Gost with config file
      command: gost -C gost-config-local.json
      args:
        chdir: /opt/gost

    # - name: Copy Gost Config filefrom local to remote
    #   ansible.builtin.copy:
    #     src: "{{ local_config_path }}"
    #     dest: "{{ remote_config_file_path }}"
